### ISSUE TITLE
Contrast/range settings from QuPath not applied in Warpy

### ISSUE THREAD

**Issue by MNM-TB** [BIOP/qupath-extension-warpy#3]
Hi,

Thank you for this extension. It is nearly perfect for our use but I stumbled on a very frustrating issue. Our mages are acquired at 11-bit and padded to 16-bit. This makes them look nearly black without adjusting the max level in QuPath. Fortunately, Qupath does this rather well automatically.  However, when I open them in the Warpy extension this shows the full range from 0 to 65k of the 16-bit images without applying the settings previously set in Qupath. 

This makes manual registration (which we need for registering H&E to the fluorescence channels) impossible and it is difficult to assess the calculated registrations.

Could this be solved to that either the Extension applies the contrast settings used in QuPath (the best option) or at least allows for an auto-contrast/normalization) to happen inside the extension?

Thanks'

**Comment by NicoKiaru** [comment]
I can try to import the display settings from QuPath, but that may take a little while ( a month or so )

Just to make sure : are you aware that you can set the min / max display in BigDataViewer, just like you do in QuPath ?

![image](https://user-images.githubusercontent.com/20223054/174074929-170e1fef-188c-4f55-b809-91bb9c7bff4c.png)

There is also an 'autoscale fixed' and 'autoscale moving' button : do they work ?

Can you find correct ranges manually ?

**Comment by MNM-TB** [comment]
Thank you for the helpful answer. In BigDataViewer/ImageJ it does work. My hope was to be able to just keep in QuPath. What I'm trying to achieve something I thought would be rather simple but appears not to be. Essentially, we have three imaging modalities imaged at three different times of the same section. I have a pipeline that then filters and co-registers them on the cellular level but I need to have a rough rigid registration and then crop them identically and finally export them as OME-TIFF. It is Image Combiner Warpy that I try to use here. This is where QuPath is a rather nice interface and my users can manage it. BigDataViewer I have a lot of issues with it is probably better suited for 3D data than WSI. 

To clarify, the contrast settings from QuPath are managed well for the single image you register to i.e., the one that is open. The issue is for the file you then add to register.

**Comment by iwbh15** [comment]
Close this issue. No further action.
