### ISSUE TITLE
No support for TMAs

### ISSUE THREAD

**Issue by lacan** [BIOP/qupath-extension-warpy#8]
TMA currently fail at being transfered. 

Consider adding them, but this would make the transfer awkward, as we could only move the center point and get some sort of estimation for the new radius odf the TMA. 

Another option is to automatically turn them into annotations, and give them the name of the TMA position they were in before

See https://forum.image.sc/t/is-it-possible-to-transfer-tma-grid-in-qupath-between-consecutive-slides-aligned-using-warpy/83168

**Comment by NicoKiaru** [comment]
Done in https://github.com/BIOP/qupath-extension-warpy/pull/9
